{"uid":"ad7877bb0693f00a","name":"Valid login with username and password","fullName":"User Login: Valid login with username and password","historyId":"27f386d9257a8e88115dafb8d2a52824","time":{"start":1731667057811,"stop":1731667077148,"duration":19337},"status":"broken","statusMessage":"NameError: name 'SUCCESS_MESSAGE' is not defined\n","statusTrace":"  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login.py\", line 30, in step_impl\n    success_message = context.driver.find_element(*SUCCESS_MESSAGE)\n                                                   ^^^^^^^^^^^^^^^\n","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"NameError: name 'SUCCESS_MESSAGE' is not defined\n","statusTrace":"  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login.py\", line 30, in step_impl\n    success_message = context.driver.find_element(*SUCCESS_MESSAGE)\n                                                   ^^^^^^^^^^^^^^^\n","steps":[{"name":"Given I open the login page","time":{"start":1731667057816,"stop":1731667066230,"duration":8414},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"When I enter username and password","time":{"start":1731667066230,"stop":1731667067024,"duration":794},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"And I click on the login button","time":{"start":1731667067024,"stop":1731667077135,"duration":10111},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"Then I should see a successful login message","time":{"start":1731667077135,"stop":1731667077147,"duration":12},"status":"broken","statusMessage":"NameError: name 'SUCCESS_MESSAGE' is not defined\n","statusTrace":"  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login.py\", line 30, in step_impl\n    success_message = context.driver.find_element(*SUCCESS_MESSAGE)\n                                                   ^^^^^^^^^^^^^^^\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":true}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":4,"hasContent":true},"afterStages":[],"labels":[{"name":"severity","value":"normal"},{"name":"feature","value":"User Login"},{"name":"framework","value":"behave"},{"name":"language","value":"cpython3"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"ad7877bb0693f00a.json","parameterValues":[]}